name: Nightly

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup GBDK
        run: |
          sudo apt-get update
          sudo apt-get install -y lcc
      - name: Build and deploy
        run: |
          make
