name: Build ROM

on: [push]

jobs:
  build_rom:
    runs-on: ubuntu-latest
    name: Compile ROM
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set path
        run: |
      - name: Build the game
        run: build.bat
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
