name: Build Game Boy Project

on:
  push:
    branches:
      - main  # Se ejecutará cuando se haga un "push" a la rama principal
  pull_request:
    branches:
      - main  # También se ejecutará en pull requests hacia la rama principal

jobs:
  build:
    runs-on: ubuntu-latest  # Usamos un entorno de Ubuntu para ejecutar la compilación
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Clona el código del repositorio

      - name: Set up GBDK
        run: |
          sudo apt update
          sudo apt install -y gbdk  # Instala GBDK en el entorno de Ubuntu

      - name: Compile Game Boy Project
        run: |
          # archivo de código fuente se llama "main.c"
          gbdk -c main.c  # Compila el archivo .c
          lcc -o main.gb main.rel  # Enlaza y crea el archivo binario (.gb)
        
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: game-boy-build
          path: main.gb  # Subimos el archivo compilado (.gb) como artefacto
