name: Build GameBoy Game

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download and install GBDK-2020 v4.3.0
        run: |
          sudo apt update
          sudo apt install -y wget tar

          # Descargar versión específica
          wget https://github.com/gbdk-2020/gbdk-2020/releases/download/4.3.0/gbdk-linux64.tar.gz
          tar -xzf gbdk-linux64.tar.gz

          # Añadir GBDK a PATH sin mover su estructura original
          echo "GBDKDIR=$PWD/gbdk" >> $GITHUB_ENV
          echo "$PWD/gbdk/bin" >> $GITHUB_PATH
          export PATH="$PWD/gbdk/bin:$PATH"

      - name: Confirm GBDK installation
        run: |
          echo "PATH: $PATH"
          which lcc
          lcc -v

      - name: Compile and build ROM
        run: |
          mkdir -p build

          # Compilar todos los .c en src/ a .o en build/
          for file in src/*.c; do
            base=$(basename "$file" .c)
            echo "Compilando $file -> build/$base.o"
            lcc -Iinclude -c -o "build/$base.o" "$file"
          done

          # Enlazar todos los .o en un solo ROM
          OBJ_FILES=$(find build -name "*.o")
          lcc -Iinclude -Wl-lhUGEDriver -o build/game.gb $OBJ_FILES

      - name: Upload ROM artifact
        uses: actions/upload-artifact@v4
        with:
          name: GBDASH.gb
          path: build/game.gb
