name: Nightly

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup GBDK
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          git clone https://github.com/gbdk-2020/gbdk-2020.git
          cd gbdk-2020
          make
          sudo make install
          cd ..
      - name: Build and deploy
        run: |
          make
