name: Build GameBoy Game

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GBDK-2020
        run: |
          sudo apt update
          sudo apt install -y wget unzip
          wget https://github.com/gbdk-2020/gbdk-2020/releases/latest/download/gbdk-linux64.tar.gz
          tar -xzf gbdk-linux64.tar.gz
          sudo mv gbdk /opt/gbdk

          echo "GBDKDIR=/opt/gbdk" >> $GITHUB_ENV
          echo "/opt/gbdk/bin" >> $GITHUB_PATH

      - name: Confirm environment
        run: |
          echo "GBDKDIR is $GBDKDIR"
          echo "PATH is $PATH"
          which lcc
          lcc -v

      - name: Compile and build ROM
        run: |
          mkdir -p build

          # Compilar todos los .c en src a .o en build/
          for file in src/*.c; do
            base=$(basename "$file" .c)
            echo "Compilando $file"
            lcc -Iinclude -c -o "build/$base.o" "$file"
          done

          # Enlazar todos los .o en build/
          OBJ_FILES=$(find build -name "*.o")
          lcc -Iinclude -Wl-lhUGEDriver -o build/game.gb $OBJ_FILES

      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: GBDASH.gb
          path: build/game.gb
